"""initial schema

Revision ID: 664ffb56d197
Revises: 
Create Date: 2025-12-17 19:22:39.869624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664ffb56d197'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('author',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('author_id', name='author_pkey')
    )
    op.create_table('book',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=255), nullable=False),
    sa.Column('publisher', sa.String(length=50), server_default=sa.text("'Невідомо'::character varying"), nullable=False),
    sa.Column('year_published', sa.Integer(), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.CheckConstraint('pages > 0', name='book_pages_check'),
    sa.PrimaryKeyConstraint('book_id', name='book_pkey'),
    sa.UniqueConstraint('title', 'language', 'publisher', 'year_published', name='uq_book_identity')
    )
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('genre_id', name='genre_pkey'),
    sa.UniqueConstraint('name', name='genre_name_key')
    )
    op.create_table('patron',
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column(
    'status',
        sa.Enum(
            'ACTIVE',
            'INACTIVE',
            'BAN',
            name='status_type_for_patron',
            create_type=False,
        ),
        server_default='ACTIVE',
        nullable=False
    ),
    sa.Column('inactivated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("email::text ~* '^[A-Za-z0-9._+%%%%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$'::text", name='email'),
    sa.CheckConstraint("length(phone_number::text) = 10 AND phone_number::text ~ '^[0-9]+$'::text", name='phone_number'),
    sa.PrimaryKeyConstraint('patron_id', name='patron_pkey'),
    sa.UniqueConstraint('email', name='patron_email_key'),
    sa.UniqueConstraint('first_name', 'last_name', 'phone_number', name='uq_patron_identity')
    )
    op.create_table('author_book',
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.author_id'], name='author_book_author_id_fkey'),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], name='author_book_book_id_fkey')
    )
    op.create_table('book_copy',
    sa.Column('book_copy_id', sa.Integer(), nullable=False),
    sa.Column('copy_number', sa.Integer(), nullable=False),
    sa.Column('available', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('available >= 0 AND available <= copy_number', name='book_copy_available_check'),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], name='book_copy_book_id_fkey'),
    sa.PrimaryKeyConstraint('book_copy_id', name='book_copy_pkey')
    )
    op.create_table('book_genres',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], name='book_genres_book_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.genre_id'], name='book_genres_genre_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'genre_id', name='book_genres_pkey')
    )
    op.create_table('notification',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('contents', sa.Text(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patron_id'], ['patron.patron_id'], name='notification_patron_id_fkey'),
    sa.PrimaryKeyConstraint('notification_id', name='notification_pkey')
    )
    op.create_table('waitlist',
    sa.Column('waitlist_id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.book_id'], name='waitlist_book_id_fkey'),
    sa.ForeignKeyConstraint(['patron_id'], ['patron.patron_id'], name='waitlist_patron_id_fkey'),
    sa.PrimaryKeyConstraint('waitlist_id', name='waitlist_pkey'),
    sa.UniqueConstraint('patron_id', 'book_id', name='uq_waitlist_patron_book')
    )
    op.create_table('wishlist',
    sa.Column('wishlist_id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=255), nullable=False),
    sa.Column('publisher', sa.String(length=50), server_default=sa.text("'Невідомо'::character varying"), nullable=False),
    sa.Column('year_published', sa.Integer(), nullable=True),
    sa.Column('added_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['patron_id'], ['patron.patron_id'], name='wishlist_patron_id_fkey'),
    sa.PrimaryKeyConstraint('wishlist_id', name='wishlist_pkey')
    )
    op.create_table('checkout',
    sa.Column('checkout_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column(
    'status',
        sa.Enum(
            'Overdue',
            'Soon',
            'OK',
            name='status_type',
            create_type=False,   # ← ТЕЖ ОБОВʼЯЗКОВО
        ),
        server_default=sa.text("'OK'::status_type"),
        nullable=False
    ),
    sa.Column('book_copy_id', sa.Integer(), nullable=False),
    sa.Column('patron_id', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['book_copy_id'], ['book_copy.book_copy_id'], name='checkout_book_copy_id_fkey'),
    sa.ForeignKeyConstraint(['patron_id'], ['patron.patron_id'], name='checkout_patron_id_fkey'),
    sa.PrimaryKeyConstraint('checkout_id', name='checkout_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checkout')
    op.drop_table('wishlist')
    op.drop_table('waitlist')
    op.drop_table('notification')
    op.drop_table('book_genres')
    op.drop_table('book_copy')
    op.drop_table('author_book')
    op.drop_table('patron')
    op.drop_table('genre')
    op.drop_table('book')
    op.drop_table('author')
    # ### end Alembic commands ###
